"""
Declarative ETL contract: the independent oracle for reconciliation tests.

Everything here is restated from the requirements and from
sql/create_tables.sql. It never imports the production transform or load
code, so a defect in those modules cannot also exist in the expected values.

- SCHEMA: target columns and types, parsed from the DDL file
- BUSINESS_KEYS: business key of every target table (the UPSERT conflict target)
- MAPPINGS: target column <- source field or business rule, per entity
- helpers that turn source-shaped (API / RAW) and processed payloads into
  comparable target-shaped rows
"""

import re
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from typing import Callable

from config.settings import PROJECT_ROOT


SCHEMA_FILE = PROJECT_ROOT / "sql" / "create_tables.sql"

SOURCE_RESOURCES = ("users", "products", "carts")
ENTITIES = ("users", "products", "carts", "cart_items")

# Business key of every target table; also the required UPSERT conflict target
BUSINESS_KEYS = {
    "users": ("user_id",),
    "products": ("product_id",),
    "carts": ("cart_id",),
    "cart_items": ("cart_id", "item_position"),
}

# Technical columns generated by the database (not part of any reconciliation)
GENERATED_COLUMNS = {"cart_items": ("cart_item_id",)}

# Optional in the source; every other business column is mandatory
OPTIONAL_COLUMNS = {"products": ("brand",)}

# Personal data: values of these columns never reach test output
SENSITIVE_COLUMNS = {
    "users": (
        "first_name", "last_name", "full_name", "email", "phone",
        "city", "state", "country", "company_name", "department",
    ),
}

# Source fields regenerated by the API on every request (never compared)
VOLATILE_SOURCE_FIELDS = {"products": ("meta.createdAt", "meta.updatedAt")}

RP_SUFFIX = " - RP"


# Schema (parsed from the DDL, the target contract)

def _parse_schema(text):
    schema, unique_keys = {}, {}

    for table, body in re.findall(
        r"CREATE TABLE IF NOT EXISTS (\w+) \((.*?)\n\);", text, re.S
    ):
        columns, keys = {}, set()

        for line in (raw.strip().rstrip(",") for raw in body.splitlines()):
            if not line or line.startswith(("--", "CONSTRAINT", "FOREIGN")):
                continue

            if line.startswith("UNIQUE"):
                keys.add(tuple(c.strip() for c in re.search(r"\((.*)\)", line).group(1).split(",")))
                continue

            name, sql_type = line.split(None, 1)
            columns[name] = sql_type.upper()

            if "PRIMARY KEY" in columns[name]:
                keys.add((name,))

        schema[table], unique_keys[table] = columns, keys

    return schema, unique_keys


SCHEMA, UNIQUE_KEYS = _parse_schema(SCHEMA_FILE.read_text(encoding="utf-8"))


def business_columns(entity):
    """Target columns that belong to the business contract (DDL order)."""
    generated = GENERATED_COLUMNS.get(entity, ())

    return [column for column in SCHEMA[entity] if column not in generated]


def mandatory_columns(entity):
    optional = OPTIONAL_COLUMNS.get(entity, ())

    return [column for column in business_columns(entity) if column not in optional]


def numeric_scale(entity, column):
    match = re.match(r"NUMERIC\(\s*\d+\s*,\s*(\d+)\s*\)", SCHEMA[entity][column])

    return int(match.group(1)) if match else None


def is_text(entity, column):
    return SCHEMA[entity][column].startswith("VARCHAR")


# Value normalization

def exact_value(entity, column, value):
    """Comparable value without any rounding (Decimal for NUMERIC columns)."""
    if value is None or numeric_scale(entity, column) is None:
        return value

    return Decimal(str(value))


def stored_value(entity, column, value):
    """
    Value the target is contractually expected to store: NUMERIC(p, s)
    columns keep s decimals (PostgreSQL rounds half away from zero, i.e.
    half-up for these non-negative values). This is the explicit schema rule;
    the database side of a comparison is never rounded.
    """
    scale = numeric_scale(entity, column)

    if value is None or scale is None:
        return value

    return Decimal(str(value)).quantize(Decimal(1).scaleb(-scale), rounding=ROUND_HALF_UP)


# Mapping specification: target column <- source field / business rule

@dataclass(frozen=True)
class Mapping:
    column: str
    rule: str
    expected: Callable
    derived: bool = False


def _get(record, path, optional=False):
    value = record

    for part in path.split("."):
        if optional and part not in value:
            return None

        value = value[part]

    return value


def copy(column, path, optional=False):
    return Mapping(column, f"copy of source '{path}'", lambda record: _get(record, path, optional))


def rule(column, description, expected):
    return Mapping(column, description, expected, derived=True)


def _discounted_price(product):
    price = Decimal(str(product["price"]))
    discount = Decimal(str(product["discountPercentage"]))

    return (price * (1 - discount / 100)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


MAPPINGS = {
    "users": (
        copy("user_id", "id"),
        copy("first_name", "firstName"),
        copy("last_name", "lastName"),
        rule("full_name", "firstName + ' ' + lastName",
             lambda user: f'{user["firstName"]} {user["lastName"]}'),
        copy("email", "email"),
        copy("phone", "phone"),
        copy("city", "address.city"),
        copy("state", "address.state"),
        copy("country", "address.country"),
        copy("company_name", "company.name"),
        copy("department", "company.department"),
    ),
    "products": (
        copy("product_id", "id"),
        rule("product_name", "title + ' - RP' (complete title kept, suffix exactly once)",
             lambda product: product["title"] + RP_SUFFIX),
        copy("category", "category"),
        copy("price", "price"),
        copy("discount_percentage", "discountPercentage"),
        rule("discounted_price", "price * (1 - discountPercentage / 100), half-up to 2 decimals",
             _discounted_price),
        copy("rating", "rating"),
        copy("stock", "stock"),
        copy("brand", "brand", optional=True),
        copy("sku", "sku"),
        copy("availability_status", "availabilityStatus"),
    ),
    "carts": (
        copy("cart_id", "id"),
        copy("user_id", "userId"),
        copy("total", "total"),
        copy("discounted_total", "discountedTotal"),
        copy("total_products", "totalProducts"),
        copy("total_quantity", "totalQuantity"),
    ),
    # Source record for a cart item: {"cart": <cart>, "position": n, "item": <cart product>}
    "cart_items": (
        copy("cart_id", "cart.id"),
        rule("item_position", "1-based position of the item in its source cart",
             lambda row: row["position"]),
        copy("product_id", "item.id"),
        copy("product_name", "item.title"),  # " - RP" applies to products only
        copy("price", "item.price"),
        copy("quantity", "item.quantity"),
        copy("total", "item.total"),
        copy("discount_percentage", "item.discountPercentage"),
        copy("discounted_total", "item.discountedTotal"),
    ),
}


def mapping(entity, column):
    return next(m for m in MAPPINGS[entity] if m.column == column)


# Source-shaped (API / RAW) payloads -> records and expected target rows

def source_records(entity, payloads):
    """Records of an entity from {resource: payload} (API or RAW shape)."""
    if entity != "cart_items":
        return payloads[entity][entity]

    return [
        {"cart": cart, "position": position, "item": item}
        for cart in payloads["carts"]["carts"]
        for position, item in enumerate(cart["products"], start=1)
    ]


def expected_rows(entity, payloads, columns=None):
    """Expected target rows derived from the source by the mapping spec."""
    selected = [
        m for m in MAPPINGS[entity]
        if columns is None or m.column in columns or m.column in BUSINESS_KEYS[entity]
    ]

    return [
        {m.column: m.expected(record) for m in selected}
        for record in source_records(entity, payloads)
    ]


# Processed payloads -> target-shaped rows

def processed_rows(entity, processed):
    """
    Rows of an entity from {resource: processed list}. Cart items are
    flattened here independently of the production load code.
    """
    if entity == "carts":
        return [{k: v for k, v in cart.items() if k != "products"} for cart in processed["carts"]]

    if entity != "cart_items":
        return processed[entity]

    return [
        {"cart_id": cart["cart_id"], "item_position": position, **item}
        for cart in processed["carts"]
        for position, item in enumerate(cart["products"], start=1)
    ]


def key_of(entity, row):
    key = tuple(row[column] for column in BUSINESS_KEYS[entity])

    return key[0] if len(key) == 1 else key


def source_key(entity, record):
    if entity == "cart_items":
        return (record["cart"]["id"], record["position"])

    return record["id"]
